name: bank_app
description: Una aplicacion bancaria de prueba.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- IDIOMA / LOCALIZACIÓN ---
  flutter_localizations:
    sdk: flutter

  # Iconos estilo iOS
  cupertino_icons: ^1.0.8

  # --- BASE DE DATOS ---
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3

  path: ^1.9.0

  # --- UTILIDADES ---
  # CAMBIO AQUÍ: Actualizado de ^0.19.0 a ^0.20.0 para evitar el error
  intl: ^0.20.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/bank.png"
  min_sdk_android: 21